config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'

  root "pages#home"
  resources :articles
  get "signup", to: "users#new"
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'login', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 3, maximu: 100 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  has_secure_password

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: {minimum: 3, maximum: 30}

  VALIDATION_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105}, format: {with: VALIDATION_EMAIL_REGEX}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find session[:user_id] if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_login
    if !logged_in?
      flash[:danger] = "You must be logged in to perform this action"
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :get_article, only: [ :show, :edit, :update, :destroy ]
  before_action :require_login, except: [ :index, :show ]
  before_action :require_same_user, only: [ :edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show

  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new article_params
    @article.user = current_user

    if @article.save
      flash[:success] = "Article was successfully created!"
      redirect_to @article
    else
      render 'new'
    end

  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully destroyed"
    redirect_to @article
  end

  private

    def get_article
      @article = Article.find params[:id]  
    end

    def article_params
      params.require(:article).permit :title, :description, category_ids: []
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:danger] = "You can edit or destroy only your own articles"
        redirect_to root_path
      end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [ :index, :show ]

  def index
    @categories = Category.paginate( page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate( page: params[:page], per_page: 5 )
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find( params[:id] )
  end

  def create
    @category = Category.new category_params
    if @category.save 
      flash[:success] = "Category was created successful"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def update
    @category = Category.find( params[:id] )

    if @category.update( category_params )
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  private

    def category_params
      params.require(:category).permit(:name)
    end

    def require_admin
      if !logged_in? || ( logged_in? && !current_user.admin? )
        flash[:danger] = "Only admin can perform tha action"
        redirect_to categories_path
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successful logged in"  
      
      redirect_to user_path(user)
    else
      flash.now[:danger] = "You have entered wrong email or password"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successful logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :update, :edit, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new user_params

    if @user.save 
      session[:user_id] = @user.id
      flash[:success] = "Welcome to my blog"
      redirect_to user_path @user
    else
      render "new"
    end

  end

  def update
    if @user.update(user_params)
      flash[:success] = "User #{@user.username} was successfully updated"
      redirect_to articles_path
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end

  def set_user
    @user = User.find params[:id]
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:danger] = "You can edit only your account"
        redirect_to root_path
      end
    end

    def require_admin
      if logged_in? && !current_user.admin?
        flash[:danger] = "Only admin users can perform this action"
        redirect_to root_path
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
  def gravatar_for user, options = { size: 80 }
    gravatar_id = Digest::MD5::hexdigest user.email
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}"
    image_tag gravatar_url, alt: user.username, class: "img-circle"
  end
end

app/views/articles/_articles.html.haml
.article-list
  - obj.each do |article|
    .well
      = link_to article.title, article_path(article), class: "article-list-title"
      .article-body
        = truncate article.description, length: 30;
        .user-info
          %small
            Created by: 
            = article.user.username if article.user
            = time_ago_in_words(article.created_at)
            ago
      .article-categories
        - if article.categories.any?
          %p
            Categories: 
            = render article.categories
      .article-actions
        - if logged_in? && (article.user == current_user || current_user.admin? )
          = link_to "Edit", edit_article_path(article), class: "btn btn-warning btn-xs"
          = link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are You Sure?"}, class: "btn btn-danger btn-xs"

app/views/articles/_form.html.haml
= render 'shared/errors', obj: @article

= form_for @article, html: {class: 'form-horizontal'} do |f|
  .form-group
    = f.label :title, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :description, class: 'control-label col-md-2'
    .col-md-10
      = f.text_area :description, class: 'form-control'
  .form-group
    .col-md-10.col-md-offset-2
      = f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|
        = cb.label( class: "checkbox-inline input_checkbox"){ cb.check_box + cb.text}
  .form-group
    .col-md-10.col-md-offset-2
      = f.submit class: 'btn btn-default'

app/views/articles/edit.html.haml
.head Edit Article
= render 'form'
 

app/views/articles/index.html.haml
.head Listing articles
= link_to "Create new article", new_article_path, class: "btn btn-success btn-xs"
%div{align: "center"}
	= will_paginate
= render 'articles', obj: @articles
%div{align: "center"}
	= will_paginate

app/views/articles/new.html.haml
.head Create Article
= render 'form'

app/views/articles/show.html.haml
.well
  .article-title 
    = @article.title
    - if @article.user
      .row
        .col-md-4
          = link_to gravatar_for(@article.user), user_path(@article.user)
          .article-title
            = link_to @article.user.username, user_path(@article.user)
 
  .article-description 
    = @article.description
  .article-categories
    - if @article.categories.any?
      %p 
        Categories: 
        = render @article.categories
  .article-actions
    = link_to "List articles", articles_path, class: "btn btn-primary btn-xs"
    - if logged_in? && (@article.user == current_user || current_user.admin?)
      = link_to "Edit", edit_article_path(@article), class: "btn btn-warning btn-xs"
      = link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are You Sure?"}, class: "btn btn-danger btn-xs"

app/views/categories/_category.html.haml
%span.badge 
  = link_to category.name, category_path(category)

app/views/categories/_form.html.haml
= render 'shared/errors', obj: @category

= form_for @category, html: {class: 'form-horizontal'} do |f|
  .form-group
    = f.label :name, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :name, class: 'form-control'
  .form-group
    .col-md-10.col-md-offset-2
      = f.submit class: 'btn btn-default'

app/views/categories/edit.html.haml
.head 
  Edit category: 
  = @category.name
= render 'form'

app/views/categories/index.html.haml
.head Listing categories
%div{ align: "center" }
  = will_paginate
  - @categories.each do |category|
    %ul.article-list.list-unstyled
      .row 
        .well.col-md-4.col-md-offset-4
          %li.article-title
            = link_to category.name, category_path(category)
          %li
            = pluralize( category.articles.count, "article" )  
  = will_paginate 

app/views/categories/new.html.haml
.head Create Category

= render 'form'

app/views/categories/show.html.haml
.article-title
  Category: 
  = @category.name
- if logged_in? && current_user.admin?  
  = link_to "Edit category", edit_category_path(@category), class: "btn btn-info btn-xs"
%div{ align: "center" }
  = will_paginate @category_articles  
= render 'articles/articles', obj: @category_articles
%div{ align: "center" }
  = will_paginate @category_articles

app/views/layouts/_footer.html.haml
.container
  %footer
    %small
      Copyright &copy; 
      %a{href: 'http://bilas.net'}http://bilas.net
    %ul
      %li
        = link_to "About", pages_about_path

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{class: "alert alert-#{name}"}
    %a.close{"data-dismiss" => "alert", :href => "#"} 
      &#215;
    = content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ type: "button", "data-toggle": "collapse", "data-target": "#bs-example-navbar-collapse-1", "aria-expanded": "false"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Blog app", root_path, id: "logo", class: "navbar-brand"
    .collapse.navbar-collapse#bs-example-navbar-collapse-2
      %ul.nav.navbar-nav
        %li
          = link_to "Articles", articles_path
        %li 
          = link_to "Users", users_path
        %li.dropdown
          %a.dropdown-toggle{"data-toggle": "dropdown", role: "button"} 
            Actions
            %span.caret
          %ul.dropdown-menu
            %li
              - if logged_in? 
                = link_to "Create article", new_article_path
        
        %li.dropdown
          %a.dropdown-toggle{"data-toggle": "dropdown", role: "button"}
            Categories
            %span.catet
          %ul.dropdown-menu
            %li
              = link_to "All Categories", categories_path
            %li.divider{ role: "separator" }
            - Category.all.each do |category|
              %li
                = link_to category.name, category_path(category)
            - if logged_in? && current_user.admin?
              %li.divider{ role: "separator" }
              %li
                = link_to "Create new category", new_category_path
      %ul.nav.navbar-nav.navbar-right
        - if logged_in?
          %li.dropdown
            %a.dropdown-toggle{"data-toggle": "dropdown", role: "button"} 
              Your profile
              - if current_user.admin?
                Admin
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to "Edit your profile", edit_user_path(current_user)
                = link_to "View your profile", user_path(current_user)

          %li
            = link_to "Log out", login_path, method: :delete
        - else
          %li 
            = link_to "Log in", login_path
          %li
            = link_to "Sign up", signup_path    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ArticleApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    .container
      = debug(params) if Rails.env.development?
      = render 'layouts/messages'
      = yield
    = render 'layouts/footer'

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.haml
.jumbotron.center
  %h1 Blog App
  = link_to "Sign up", "signup", class: "btn btn-primary btn-lg"

app/views/shared/_errors.html.haml
- if obj.errors.any?
  .alert.col-md-offset-2.col-md-10.alert-danger{:role => "alert"}
    .alert-title
      %h2.panel-title
        Following 
        = pluralize(obj.errors.full_messages.length, 'error')
    %ul
      - obj.errors.full_messages.each do |msg|
        %li
          = msg

app/views/users/_form.html.haml
= render 'shared/errors', obj: @user

= form_for @user, html: {class: 'form-horizontal'} do |f|
  .form-group
    = f.label :username, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :username, class: 'form-control', placeholder: "Enter username"
  .form-group
    = f.label :email, class: 'control-label col-md-2'
    .col-md-10
      = f.email_field :email, class: 'form-control', placeholder: "Enter email"
  .form-group
    = f.label :password, class: 'control-label col-md-2'
    .col-md-10
      = f.password_field :password, class: 'form-control', placeholder: "Enter password"
  .form-group
    .col-md-10.col-md-offset-2
      = f.submit class: 'btn btn-default'

app/views/users/edit.html.haml
.head 
  Edit user
  = " #{@user.username}"
= render 'form'

app/views/users/index.html.haml
.h1 Listing users
%div{ align: "center" }
  = will_paginate
- @users.each do |user|
  .row
    .well.col-md-4.col-md-offset-4.center
      = link_to gravatar_for(user), user_path(user)
      .article-title
        = link_to user.username, user_path(user)
      %small
        User has 
        = pluralize(user.articles.length, 'articles') if user.articles
        articles
      - if logged_in? && current_user.admin?  
        = link_to "Delete this user", user_path(user) , method: :delete, data: { confirm: "Are you sure?" }
%div{ align: "center" }
  = will_paginate        

app/views/users/new.html.haml
.head Sign Up
= render 'form'

app/views/users/show.html.haml
.head.center 
  Welcome to 
  = @user.username
  page
.row.center  
  = gravatar_for @user, options = { size: 150 }
%div{align: "center"}
  = will_paginate @user_articles         
= render 'articles/articles', obj: @user_articles
%div{align: "center"}
  = will_paginate @user_articles